<?php

class VendaBo
{

    private $venda_dao;
    private $table;
    private $class;
    private $dbh;
    private $key;

    public function __construct($dbh) {
        $this->venda_dao = new VendaDao();
        $this->table = 'venda';
        $this->class = 'Venda';
        $this->dbh = $dbh;
        $this->key = 'id';
    }

    public function exec($options = null)
    {
        return $this->venda_dao->exec($this->dbh, $this->class, $options); // TODO: Change the autogenerated stub
    }

    public function all()
    {
        $this->venda_dao->all($this->table);
        return $this;
    }

    public function where($options)
    {
        $this->venda_dao->where($options); // TODO: Change the autogenerated stub
        return $this;
    }

    public function order($options)
    {
        $this->venda_dao->order($options); // TODO: Change the autogenerated stub
        return $this;
    }

    public function find($value, $operator = '=')
    {
        $this->venda_dao->find($this->key, $value, $operator); // TODO: Change the autogenerated stub
        return $this;
    }

    public function update($table_columns, $key)
    {
        $this->venda_dao->update($this->table, $table_columns, $key); // TODO: Change the autogenerated stub
        return $this;
    }

    public function create($table_columns)
    {
        $this->venda_dao->create($this->table, $table_columns); // TODO: Change the autogenerated stub
        return $this;
    }

    public function save($object)
    {
        return $this->venda_dao->save($this->dbh, $this->table, $this->class, $object);
    }

    public function setCreateColumns($id, $request) {
        return $this->venda_dao->setCreateColumns($this->dbh, $this->table, $this->class, $id, $request);
    }
    
    public function setUpdateColumns($id, $request) {
        return $this->venda_dao->setUpdateColumns($this->dbh, $this->table, $this->class, $id, $request);
    }

    public function first() {
        $this->venda_dao->first();
        return $this;
    }

    public function delete($object) {

        $this->venda_dao->delete($this->table, $this->key, $object->id);
        return $this;

    }

    public function execwoclass($options = null) {

        return $this->venda_dao->execwoclass($this->dbh, $options); // TODO: Change the autogenerated stub

    }

    public function select($columns) {

        $this->venda_dao->select($this->table, $columns);
        return $this;

    }

    public function join($table2, $key1, $key2) {

        $this->venda_dao->join($this->table, $table2, $key1, $key2);
        return $this;
    }

    public function group($column) {

        $this->venda_dao->group($column);
        return $this;

    }

    public function joinwopktable($table1, $table2, $key1, $key2) {

        $this->venda_dao->join($table1, $table2, $key1, $key2);

        return $this;

    }
    
    public function getLastInsertedId() {
        return $this->venda_dao->getLastInsertedId($this->dbh);
    }
    
    public function trataNumero($numero) {
        return $this->venda_dao->trataNumero($numero);
    }

    public function custom($sql) {

        $this->venda_dao->custom($sql);
        return $this;

    }

    public function createiatable($table, $table_columns) {
        $this->venda_dao->createiatable($table, $table_columns);
        return $this;
    }


}